// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckPort(arg1:string,arg2:number):Promise<boolean>;

export function ClearMessages(arg1:number):Promise<void>;

export function Connect(arg1:number):Promise<void>;

export function CreateConnection(arg1:models.Connection):Promise<number>;

export function DeleteConnection(arg1:number):Promise<void>;

export function Disconnect(arg1:number):Promise<void>;

export function ExportConnections(arg1:Array<number>):Promise<string>;

export function ExportConnectionsToFile(arg1:Array<number>):Promise<string>;

export function GetClientID(arg1:number):Promise<string>;

export function GetConnection(arg1:number):Promise<models.Connection>;

export function GetConnectionStatus(arg1:number):Promise<boolean>;

export function GetConnections():Promise<Array<models.Connection>>;

export function GetHostInfo():Promise<string>;

export function GetMessages(arg1:number,arg2:string,arg3:number):Promise<Array<models.Message>>;

export function GetNumericMessages(arg1:number,arg2:string,arg3:number):Promise<Array<models.Message>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetTopicTree(arg1:number):Promise<models.TopicNode>;

export function GetVersion():Promise<string>;

export function ImportConnections(arg1:string):Promise<Array<number>>;

export function ImportFromOldVersion(arg1:string):Promise<number>;

export function SearchConnections(arg1:string):Promise<Array<models.Connection>>;

export function SearchMessages(arg1:number,arg2:string,arg3:boolean):Promise<Array<models.Message>>;

export function SendMessage(arg1:models.SendMessageRequest):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function Subscribe(arg1:number,arg2:string,arg3:number):Promise<void>;

export function Unsubscribe(arg1:number,arg2:string):Promise<void>;

export function UpdateConnection(arg1:models.Connection):Promise<void>;
