// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1, arg2) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2);
}

export function ClearMessages(arg1) {
  return window['go']['main']['App']['ClearMessages'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExportConnections(arg1) {
  return window['go']['main']['App']['ExportConnections'](arg1);
}

export function ExportConnectionsToFile(arg1) {
  return window['go']['main']['App']['ExportConnectionsToFile'](arg1);
}

export function GetClientID(arg1) {
  return window['go']['main']['App']['GetClientID'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetConnectionStatus(arg1) {
  return window['go']['main']['App']['GetConnectionStatus'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetNumericMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNumericMessages'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTopicTree(arg1) {
  return window['go']['main']['App']['GetTopicTree'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConnections(arg1) {
  return window['go']['main']['App']['ImportConnections'](arg1);
}

export function ImportFromOldVersion(arg1) {
  return window['go']['main']['App']['ImportFromOldVersion'](arg1);
}

export function SearchConnections(arg1) {
  return window['go']['main']['App']['SearchConnections'](arg1);
}

export function SearchMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchMessages'](arg1, arg2, arg3);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2, arg3);
}

export function Unsubscribe(arg1, arg2) {
  return window['go']['main']['App']['Unsubscribe'](arg1, arg2);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
